Runs the action on validate PR

diff --git a/.github/workflows/validate-pr.yml b/.github/workflows/validate-pr.yml
--- a/.github/workflows/validate-pr.yml
+++ b/.github/workflows/validate-pr.yml
@@ -51,6 +51,62 @@ jobs:
         env:
           TEST_SSM_PREFIX: /test/ssm2ssm
 
+  run-action:
+    name: 'Runs the github action'
+    runs-on: ubuntu-latest
+    steps:
+      - name: 'Checkout'
+        uses: actions/checkout@v2
+
+      - name: 'Configure AWS credentials'
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-region: us-east-1
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ssm2ssm-tests
+
+      - name: 'Deletes existing parameters'
+        run: |
+          set -eo pipefail
+
+          aws ssm get-parameters-by-path \
+            --path "$SSMPATH" \
+            --no-cli-pager \
+          | jq -r '.Parameters[].Name' \
+          | while read -r param; do
+            echo "[INFO ] Deleting parameter: $param" >&2
+            aws ssm delete-parameter \
+              --name "$param" 2>&3
+          done
+
+          echo "[INFO ] Sleeping for 30 seconds to allow SSM to propagate" >&2
+          sleep 30
+        env:
+          SSMPATH: /test/ssm2ssm-action
+
+      - name: 'Run action'
+        uses: ./
+        with:
+          input-path: /aws/service/global-infrastructure/regions
+          output-path: /test/ssm2ssm-action
+
+      - name: 'Validate a parameter'
+        run: |
+          set -eo pipefail
+
+          aws ssm get-parameter \
+            --name "$SSMPATH/us-east-1" \
+            --with-decryption \
+            --no-cli-pager \
+          | jq -r '.Parameter.Value' \
+          | while read -r value; do
+            [ "$value" == us-east-1 ] || {
+              echo "[ERROR] value is not us-east-1" >&2
+              exit 1
+            }
+          done
+        env:
+          SSMPATH: /test/ssm2ssm-action
+
   # precommit:
   #   name: 'Run precommit check'
   #   runs-on: ubuntu-latest
